apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-deployment
spec:
  selector:
    matchLabels:
      app: customer-support
  template:
    metadata:
      labels:
        app: customer-support
    spec:
      containers:
      - name: customer-support
        image: "europe-west1-docker.pkg.dev/fun-7-gcloud-project/fun-7-gcloud-project-repo/customer-support"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 8080
            path: /swagger-ui/index.html
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
          - name: SPRING_CONFIG_LOCATION
            value: "/app/deployments/config/"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: application-config
            mountPath: "/app/deployments/config"
            readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: customer-support-configmap-generator
            items:
            - key: application-kube.properties
              path: application-kube.properties