apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-deployment
spec:
  selector:
    matchLabels:
      app: customer-support
  template:
    metadata:
      labels:
        app: customer-support
    spec:
      containers:
      - name: customer-support
        image: fun-7-backend/customer-support:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: application-config
            mountPath: "/app/config"
            readOnly: true
          - mountPath: /tmp
            name: tmp
      volumes:
        - name: application-config
          configMap:
            name: customer-support-configmap-generator
            items:
            - key: service.properties
              path: application.properties
            - key: logback.xml
              path: logback.xml