apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "ads-router"
  namespace: "default"
spec:
  defaultBackend:
    service:
      name: "ads-service"
      port:
        number: 80
status:
  loadBalancer: { }
