apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-deployment
spec:
  selector:
    matchLabels:
      app: multiplayer
  template:
    metadata:
      labels:
        app: multiplayer
    spec:
      containers:
        - name: multiplayer
          image: "europe-west1-docker.pkg.dev/fun-7-gcloud-project/fun-7-gcloud-project-repo/multiplayer"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /swagger-ui/index.html
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_CONFIG_LOCATION
              value: "/app/deployments/config/"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: application-config
              mountPath: "/app/deployments/config"
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: multiplayer-configmap-generator
            items:
              - key: application-kube.properties
                path: application-kube.properties