apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-deployment
spec:
  selector:
    matchLabels:
      app: multiplayer
  template:
    metadata:
      labels:
        app: multiplayer
    spec:
      containers:
      - name: multiplayer
        image: fun-7-backend/multiplayer:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
